### ISSUE TITLE
Priority queue no longer works

### ISSUE THREAD

**Issue by skrubzilla** [Igirisujin/igicore-queue-standalone#5]
now no matter what it sets everyone to 100 when they join even if you are on the priority list with a different number

**Comment by IgiCodes** [comment]
Just downloaded the latest release and set it up on a fresh server; I can't recreate this issue. Feel free to post your queueSettings.yml file and I can see if there are any issues in the format.

**Comment by IgiCodes** [comment]
Problem was on the user end, issues with steam was causing the server to not pick up their steamid for some reason.
